### PR TITLE
Fixes Issue #226

### PR DESCRIPTION
**Pull request by natcrossman**
Here is the list of changes that would get integrated into the project, if this pull request gets accepted:
<p  align="center">1. <strong>Issue #226 is Fixed</strong> </p>
<p  align="center">a.	Both Bug 1  and Bug 2 </p>
<p  align="center">2.<strong>Ensures version constraint are followed</strong></p>
<p  align="center">a.	Throws exception if current version of Java is not compatible </p>
<p  align="center">3.<strong>Removes redundant code in .classpath</strong></p>
<p  align="center">a.	Combines two buildscripts </p>
<p  align="center">4.<strong>Removes duplicate line of XML code inside of RaiderPlanner.iml</strong></p>

### CODE REVIEW

**Comment by natcrossman** [comment]
This bug took an inordinate amount of time to figure out and fix. I've, sadly, been working on it since class ended yesterday and haven't left campus YET! And, this depressingly doesn't count the time I spent researching at home. I feel like the Gradle documentation is severely lacking. Anyways, I hope everything is okay with this pull request. Don't hesitate to inform me, if I need to change anything.
Regards Nat

**Comment by rsanchez-wsu** [comment]
@natcrossman So, you are headed in the right direction, but there is a more elegant approach. The issue I have with your implementation is that it results in a change to `.classpath` that the developer may inadvertently commit and put into a pull request. The approach I take is to remove the version-specific JRE container that Gradle conjures up, and replace it with the generic JRE container I would like to have for our project configuration. Here is the change I propose to make to your pull request:
```
 }
 
 /**
- * This chagnes the Gradle plugin's Access Rule when they are set to default
- * 
+ * Keep Gradle from rewriting the generic default JRE container configuration
  */
-eclipse.classpath.file.whenMerged {
-    def container = entries.find { it.path.contains 'org.eclipse.jdt.launching.JRE_CONTAINER' }
-    container.accessRules << new org.gradle.plugins.ide.eclipse.model.AccessRule("accessible", "javafx/**")
+eclipse.classpath.file.whenMerged { classpath ->
+       classpath.entries.removeAll { entry -> entry.kind == 'con' }
+       classpath.entries.add(new Container('org.eclipse.jdt.launching.JRE_CONTAINER'))
 }
```
If you do not object, I will merge your pull request and then apply this additional change on top of it.

**Comment by natcrossman** [comment]
That was actually one of the first ideas I tried. However, I read online that it wasn't the greatest idea to do it that way. Instead, people were saying just push the changed classpath up to our remote repository. Additionally, right now the way your code works it will also remove  <classpathentry kind="con" path="org.eclipse.buildship.core.gradleclasspathcontainer"/> would this be a problem?

**Comment by natcrossman** [comment]
Ultimately, If this is the better way of doing it then I have no problem with it.

**Comment by natcrossman** [comment]
Below is the segment of code that I used originally to fix the problem. This code simply removes the unwanted classpast that gets added.

```
eclipse {
    classpath {
        file.whenMerged    { classpath ->
        classpath.entries.removeAll { entry -> entry.path == 'org.eclipse.jdt.launching.JRE_CONTAINER/org.eclipse.jdt.internal.debug.ui.launcher.StandardVMType/JavaSE-1.8/' }
		}
        // I add the correct
        containers 'org.eclipse.jdt.launching.JRE_CONTAINER'
    }
}



```

**Comment by natcrossman** [comment]
Also, I've been playing around with your Snippet of code and I couldn't get it to work in my Eclipse project. 

Ultimately, If this is the better way of doing it then I have no problem with it.

**Comment by rsanchez-wsu** [comment]
@natcrossman I understand why it might be considered bad form to mangle the classpath configuration in that way. If we were a commercial team with a mandated baseline of supported development tools, I would feel like pushing the changed `.classpath` into Git was OK. However, everybody has different configurations on their machines and we end up with potentially 30-ish new developers every semester, so I want the project configuration to be flexible enough to accommodate those setups without much trouble. I am curious as to how you are testing the change and in what way it doesn't work for you.

**Comment by rsanchez-wsu** [comment]
@natcrossman I think I know why my code snippet might not work for you. This import is required at the top of `build.gradle`:
```
import org.gradle.plugins.ide.eclipse.model.Container
```

**Comment by rsanchez-wsu** [comment]
@natcrossman I am not opposed to the more precise specification of the classpath container. If you want, go ahead and update your pull request and I will merge it. If not, I can apply the additional change after I merge.

**Comment by natcrossman** [comment]
Let's just leave it the way you did it. As theoretically the path could be slightly different depending on what machine you are running. Anyways I hope I wasn't bothering you too much. I am always curious about what is the optimal or best approach.

**Comment by rsanchez-wsu** [comment]
@natcrossman No bother at all.

**Pull request merged**
