### PR TITLE
Program closes without throwing errors to console Resolves: #303

### PR DESCRIPTION
**Pull request by GGanris**
The program can now be exited at the create account window without having errors in the console or an alert window pop up.

### CODE REVIEW

**Comment by gbdodds** [comment]
Doesn't seem to cause any adverse behavior when I implement this.

**Comment by logankrause16** [comment]
Great quality of life fix. No errors on my end.

**Comment by GGanris** [comment]
Cleaned up the code to get rid of the unneeded throws after the system.exit. It still needed to have a throws IOException or else line 111 would have an error.

**Comment by rsanchez-wsu** [comment]
I like this.  Thanks for taking care of it.

**Pull request merged**
