### PR TITLE
Change module colors and design

### LINKED ISSUE #57: Close notification menu when clicked away from
The notification menu currently can only be closed by clicking on the notification button. I think the menu should close if you click anywhere else on the planner, given that the menu covers the upper right portion of the page and it is somewhat inconvenient that the notifications when clicked open on the center of the screen, and the only way to close the panel is to click the icon.

### LINKED ISSUE #90: Change dashboard module colors
Colors on the modules on the dashboard should change based on progress of the module. For example, 0% would be red, 100% would be green, and the others in between those would have in-between colors. The task would be to create an algorithm to compute the RGB values based on the percentage.

Also, make the modules Material Design, and remove the "View" buttons and instead make the entire box clickable.

Here is a mockup of what I mean by making it "material design". Still very much a work in progress.
screenshot_20171005-180058

And here is how they would be colored according to progress.
screenshot_20171006-163403

### LINKED ISSUE #118: Allow window to resize smaller than 1000px height
Currently the minimum height is 1000px, which is very high and works very poorly on screens that are lower than FHD. I am claiming this issue.

### LINKED ISSUE #119: Make modules scrollable when window gets too small
Make the modules on the dashboard resize along with the window itself. Also, use a FlowPane instead of a GridPane to allow to modules to shrink and react dynamically inside the window.

I am claiming this issue.

### LINKED ISSUE #120: Make window size based on screen resolution.
Make the window startup size based on the resolution of the screen it is being viewed on. I claim this issue.

### LINKED ISSUE #127: Add files to gitignore
Add all ICS files, all .dat files, and the import_report.txt file to .gitignore.

### PR DESCRIPTION
**Pull request by Aashishkebab**
This pull request has several major changes to the program's appearance as well as underlying backend GUI. The GUI is created differently in some cases.

Make the modules change colors based on progress, and implement material design. This fixes #90. It is also my submission for project 3.
screenshot_20171010-181822

Also, make the modules scrollable when the window gets too small. This fixes #119.
Also, allow the window to be resized smaller. This fixes #118.
Also, set window startup dimensions based on screen resolution. This fixes #120.
Also, make the modules pop out when hovering over them.
Also, fix icon background colors.
Also, rearrange the icons at the top so that when the window is squished, the notification icon stays visible and isn't added to the overflow menu.
Also, adds files to gitignore, which fixes #127.
Also, close hamburger menu when clicked away from. This fixes #57.

This pull request modifies almost all of the changes in commit d6cf727, part of pull request #66 (which was created to address #40). The reason is that commit d6cf727 only created a workaround to the modules issue, this pull request technically solves the underlying issue by surrounding the modules with a ScrollPane.

### CODE REVIEW

**Comment by rsanchez-wsu** [comment]
@Aashishkebab Please have a look at the build output and correct the failure.

**Comment by Aashishkebab** [comment]
It says that it is a checkstyle error, with the error being that the class UIManager has too many capital letters in a row. Which doesn't really make much sense to me considering the fact that I didn't change this at all.
screenshot_20171014-233934

**Comment by Aashishkebab** [comment]
Checkstyle issues have been fixed.

**Comment by Aashishkebab** [comment]
Six of the commits are dedicated to checkstyle fixes.

**Pull request merged**
