### PR TITLE
Fixes mainContent resizing

### LINKED ISSUE #91: Calendar size bug
screenshot_20171006-150537
There is a bug with the calendar. When you resize the window while still in the Study Dashboard, and theen switch to calendar view, the calendar has shrunk.

### PR DESCRIPTION
**Pull request by RachelHill8**
Fixes #91

### CODE REVIEW

**Comment by RachelHill8** [comment]
This pull request is no longer needed with the UI changes in #106

**Comment by Aashishkebab** [comment]
@RachelHill8 Actually I think it still is necessary, as #106 did not fix #91, and it still is an issue. It's the issue where the content inside the windows get smaller every time you resize and switch to another screen. 
I did not fix this in my pull request, as I knew you were working on it.

**Comment by RachelHill8** [comment]
Ok I will have to look at it deeper because with the new panes the majority of this doesn't work.

**Comment by Aashishkebab** [comment]
@RachelHill8 Does it still work with the other views? I didn't modify the other stuff, such as the calendar view, milestones, modules, etc. So the fix for those should still work.

**Comment by RachelHill8** [comment]
Yes. So the only issue might be the modules on the dashboard.

**Comment by Aashishkebab** [comment]
@RachelHill8 I changed the GridPane into a FlowPane, and then added a ScrollPane inside of it. 

I wonder why changing it to FlowPane breaks your code. Unfortunately, the FlowPane is necessary in this case.

Maybe the static references you make to GridPane you could instead make to FlowPane. I don't know though. Regardless, I think your pull request is still good and necessary.

**Comment by RachelHill8** [comment]
I had moved some of the titles into the Gridpane. But I only had to add one line and now the modules aren't moving as well. Hopefully it didn't mess up anything with the changes.

**Comment by Aashishkebab** [comment]
@RachelHill8 I just merged your file temporarily, into my local repo, and everything seems to work fine. There is a Slack group to discuss UI Design if you'd like to join. There are several students in there already, and Roberto is in there too. You could throw your questions in there and someone is bound to know the answer. https://raiderplanner.slack.com/messages/C7M6VEY3H

**Pull request merged**
