### PR TITLE
Fixes: Issue #317 , changes to UI

### PR DESCRIPTION
**Pull request by iWinfrey**
Addressed the issue #317 for the UI change on the startup window for
creating an account when running the program. Only made changes to help
clarify what each of the textfields require the user to enter. Down
below I included screenshots of what the window looked like before and
then after the changes.

Before changes:
beforeuiraiderplanner

After changes:
afteruiraiderplanner

### CODE REVIEW

**Comment by rsanchez-wsu** [comment]
@iWinfrey What efforts did you make to prevent duplication of effort with other issues that were being worked on in the same time frame?  I specifically requested this in response to your write up of #317.

**Comment by iWinfrey** [comment]
Oh right I forgot to include that before I began starting this project. After I finished it and done the pull request, I wasn't sure if I could still do that or not at that point in the project completion

**Comment by rsanchez-wsu** [comment]
I don't necessarily disagree with your changes.  However, I would like some input from other team members.  Feel free to hit up folks in Slack or whatever and get them to comment on this pull request and/or the issue.

**Comment by iWinfrey** [comment]
Okay I'll be sure to do so. For some reason my Authors page is conflicting every time it tries to merge and I don't know what the issue is. It works fine whenever I commit to the pull request and passes the validation check but for some reason it keeps showing conflicts some time afterwards. I'll try to ask about this issue on slack but I thought I fixed it the first time

**Comment by mikeknows** [comment]
The prompt text for the salutation field is more concise than before. I think the family name checkbox and text should be removed completely. Make the salutation box smaller and make the full name field larger or split the full name into two fields. Could fix the regex so the salutation field picks up a period.

What about someone who has a Jr., Sr., or III on the end? Doesn't function currently in that aspect. That could be added as a field and it would make up the missing space of the checkbox/text.

I don't think the e-mail is used for anything specifically right now only thing calling on it is methods to verify it, making it required at this time is unnecessary in my opinion but I think it's a good idea for the future.

**Comment by iWinfrey** [comment]
image

I have included a dropdown menu for the salutations. It will include the three items of "Mr., Mrs., and Dr." This should hopefully make things easier for the user to select a prefix name for this field. I was only able to get the dropdown setup and the validation but the output still does not include the salutation on the welcome screen.

**Pull request merged**
